import {mkdir,readFile,writeFile,rename,unlink} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {randomUUID} from 'node:crypto';

/** Private filesystem object store; keys are generated by the server, never client paths. */
export async function createDiskStorage(directory) {
 const root=resolve(directory);await mkdir(root,{recursive:true,mode:0o700});
 const target=key=>{if(!/^[a-f0-9-]{36}\.(png|jpg|webp)$/.test(key))throw new Error('Invalid storage key');return join(root,key);};
 return {
  async put(key,bytes) {
   const path=target(key),temporary=join(root,`.pending-${randomUUID()}`);
   try {await writeFile(temporary,bytes,{flag:'wx',mode:0o600});await rename(temporary,path);}
   finally {await unlink(temporary).catch(error=>{if(error.code!=='ENOENT')throw error;});}
  },
  get:key=>readFile(target(key)),
  delete:async key=>{try{await unlink(target(key));}catch(error){if(error.code!=='ENOENT')throw error;}}
 };
}
